# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the industrial I/O buffer implementations
#

# When adding new entries keep the list in alphabetical order
obj-m += industrialio-buffer-cb.o
obj-m += industrialio-buffer-dma.o
obj-m += industrialio-buffer-dmaengine.o
obj-m += industrialio-hw-consumer.o
obj-m += industrialio-triggered-buffer.o
obj-m += kfifo_buf.o
