syntax on
set number
set softtabstop=4
set autoindent
set noexpandtab
set tabstop=4
"set shiftwidth=4
set tags+=/home/pi/zengjf/userland-master/tags
set tags+=/home/pi/zengjf/rpi-sense/tags
set tags+=/home/pi/zengjf/iio_src/iio_src/tags
